package com.om.ibg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Testing implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String one;

	public Testing() {
	}

	public java.lang.String getOne() {
		return this.one;
	}

	public void setOne(java.lang.String one) {
		this.one = one;
	}

	public Testing(java.lang.String one) {
		this.one = one;
	}

}