package com.om.ibg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Testing implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Testing() {
    }




}