package com.techm.bm.om.brms;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Test implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String one;

	private java.lang.String two;

	public Test() {
	}

	public java.lang.String getOne() {
		return this.one;
	}

	public void setOne(java.lang.String one) {
		this.one = one;
	}

	public java.lang.String getTwo() {
		return this.two;
	}

	public void setTwo(java.lang.String two) {
		this.two = two;
	}

	public Test(java.lang.String one, java.lang.String two) {
		this.one = one;
		this.two = two;
	}

}